import {
  IconAIProductivity,
  IconAnalytics,
  IconConsulting,
  IconSecurity,
  IconDataMgmt,
  IconHybridInfra,
} from '../../components/icons';
import type { SubProductContent } from '../../app/pages/_shared/SubProductPage';
import { PATHS } from '../../lib/routes';
import { mailto } from '../../lib/site';

export const dataReporting: SubProductContent = {
  heroEyebrow: 'IDMB Data · Regulatory reporting',
  heroTitle: <>The regulator return,<br />generated by the ledger</>,
  heroLede:
    'Pre-built statutory reports for the regulators IDMB customers file with - refreshed in lockstep with the ledger, exported audit-grade and tamper-evident.',
  heroPrimary:   { label: 'Read the reporting docs', href: PATHS.developersDocs },
  heroSecondary: { label: 'Talk to compliance team', href: mailto('sales', 'IDMB Reporting enquiry') },
  heroVariant: 'centered',
  heroTone: 'tinted',
  capabilitiesVariant: 'minimal',
  capabilitiesBg: 'default',
  howVariant: 'circles',
  howBg: 'default',
  relatedVariant: 'horizontal',

  capabilitiesHeading: 'Capabilities',
  capabilities: [
    { title: 'Statutory reports',     desc: 'Pre-built returns for the regulators IDMB customers file with.',          href: PATHS.dataReporting,  icon: IconAIProductivity },
    { title: 'Refresh in lockstep',   desc: 'Reports refresh as the ledger does - no batch reconciliation gap.',         href: PATHS.dataReporting,  icon: IconHybridInfra },
    { title: 'Audit-grade exports',   desc: 'Tamper-evident, time-stamped exports of any ledger slice.',                 href: PATHS.dataReporting,  icon: IconSecurity },
    { title: 'Revenue intelligence',  desc: 'Unit economics, take-rate and corridor-level P&L from the same ledger.',     href: PATHS.dataReporting,  icon: IconAnalytics },
    { title: 'Schedule & deliver',    desc: 'Scheduled report generation and delivery to your regulator portal of choice.', href: PATHS.dataReporting, icon: IconDataMgmt },
    { title: 'Custom report builder', desc: 'Build your own reports on the same primitives the IDMB team uses.',         href: PATHS.dataReporting,  icon: IconConsulting },
  ],

  howHeading: 'How it works',
  steps: [
    { title: 'Pick a report',     desc: 'From the IDMB catalogue or build your own from primitives.' },
    { title: 'Configure',         desc: 'Pick currency, region, regulator and frequency.' },
    { title: 'Schedule & deliver', desc: 'Reports refresh in lockstep with the ledger and deliver on cadence.' },
    { title: 'Audit',             desc: 'Every report is tamper-evident and reproducible against any ledger slice.' },
  ],

  quotePlaceholder: true,
  quote: {
    quote:
      'Our regulator review took two days, not two months. The IDMB audit trail let us answer every question with a deterministic export.',
    name: 'Aisha Mensah',
    role: 'CTO',
    company: 'Northbank',
    storyHref: PATHS.customerNorthbank,
  },

  pricing: {
    headline: 'Bundled into the IDMB platform fee',
    detail: 'Report generation, scheduling and audit-grade exports are included.',
    href: PATHS.pricingData,
  },

  relatedHeading: 'Related modules',
  related: [
    { title: 'Data lake & warehouse', desc: 'The same ledger streams reports read from.',     href: PATHS.dataLake,        icon: IconHybridInfra },
    { title: 'Compliance, KYC & AML', desc: 'KYC, AML and sanctions on the same platform.',   href: PATHS.bankingCompliance, icon: IconSecurity },
    { title: 'Trust centre',          desc: 'IDMB security, compliance and licences in one place.', href: PATHS.trust,             icon: IconConsulting },
  ],

  cta: {
    heading: 'Pass your next regulator return on autopilot',
    subheading: 'Open a sandbox to see the report catalogue, or talk to our team about your specific reporting obligations.',
    primary:   { label: 'Open the sandbox',          href: PATHS.developersSandbox },
    secondary: { label: 'Talk to the compliance team', href: mailto('sales', 'IDMB Reporting enquiry') },
  },
};
