import type { ResourceEntry } from '../types';

export const BLOG_POSTS: ResourceEntry[] = [
  {
    kind: 'blog',
    slug: 'core-banking-apis-what-actually-matters',
    title: 'Core banking APIs: what actually matters at scale',
    date: '2026-04-22',
    author: { name: 'Priya Nair', role: 'Head of Payments, IDMB' },
    excerpt: "Most core banking API debates get stuck on REST vs event-driven. Here's the harder question: what does your ledger guarantee under partition?",
    readTime: '7 min read',
    tags: ['Banking', 'Architecture', 'APIs'],
    load: () => import('./core-banking-apis-what-actually-matters.mdx'),
  },
  {
    kind: 'blog',
    slug: 'embedded-finance-what-operators-get-wrong',
    title: "Embedded finance: what operators get wrong about compliance",
    date: '2026-04-08',
    author: { name: 'Kwame Asante', role: 'Chief Compliance Officer, IDMB' },
    excerpt: "Embedding financial products into a non-financial app sounds simple. The compliance surface isn't. Here's where operators run into trouble.",
    readTime: '9 min read',
    tags: ['Compliance', 'Embedded Finance', 'Regulatory'],
    load: () => import('./embedded-finance-what-operators-get-wrong.mdx'),
  },
  {
    kind: 'blog',
    slug: 'real-time-payments-settlement-finality',
    title: 'Real-time payments and the settlement finality problem',
    date: '2026-03-25',
    author: { name: 'Priya Nair', role: 'Head of Payments, IDMB' },
    excerpt: "Real-time payment schemes promise instant money. Most of them don't promise irrevocable money. Understanding the difference determines your fraud and liquidity model.",
    readTime: '6 min read',
    tags: ['Payments', 'Architecture', 'Risk'],
    load: () => import('./real-time-payments-settlement-finality.mdx'),
  },
  {
    kind: 'blog',
    slug: 'mobile-money-modernisation-not-replacement',
    title: "Mobile money modernisation: why it's not a replacement problem",
    date: '2026-03-11',
    author: { name: 'Amara Osei', role: 'CEO, IDMB' },
    excerpt: "Mobile money operators that have tried 'rip and replace' mostly failed. The successful modernisations kept the brand, agents, and float — and changed the ledger underneath.",
    readTime: '8 min read',
    tags: ['Mobile Money', 'Strategy', 'Banking'],
    load: () => import('./mobile-money-modernisation-not-replacement.mdx'),
  },
  {
    kind: 'blog',
    slug: 'card-issuing-authorisation-engine-deep-dive',
    title: 'Card authorisation engine: how programmable rules work at 50M cards',
    date: '2026-02-19',
    author: { name: 'Tunde Adeyemi', role: 'CTO, IDMB' },
    excerpt: "Every card transaction runs through an authorisation decision in under 100ms. Here's what that decision tree looks like and how IDMB exposes it via API.",
    readTime: '10 min read',
    tags: ['Cards', 'Engineering', 'Architecture'],
    load: () => import('./card-issuing-authorisation-engine-deep-dive.mdx'),
  },
  {
    kind: 'blog',
    slug: 'wallet-infrastructure-for-super-apps',
    title: 'Wallet infrastructure for super-apps: the multi-tenancy problem',
    date: '2026-02-03',
    author: { name: 'Amara Osei', role: 'CEO, IDMB' },
    excerpt: "A super-app wallet needs to serve millions of users, multiple merchant types, and regulatory requirements across markets — all from one integration. Here's how we architect that.",
    readTime: '7 min read',
    tags: ['Wallets', 'Architecture', 'Super-apps'],
    load: () => import('./wallet-infrastructure-for-super-apps.mdx'),
  },
];
